//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookClub.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public int NumberOrder { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public System.DateTime DateOrder { get; set; }
        public decimal FinalSum { get; set; }
        public int PointId { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Points Points { get; set; }
        public virtual Products Products { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
